# Generated by Django 4.2.4 on 2023-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='room',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='chats',
            unique_together={('room', 'chat_id')},
        ),
    ]
